#!/bin/bash
# Guia: quais contas criar e como ativar a divulgação 24/7
echo "===================================================="
echo " DIVULGAÇÃO 24/7 — BTC WEATHER PANEL (X + Instagram)"
echo "===================================================="
echo ""
echo "PASSO 1 — Criar as contas (grátis):"
echo "  X (Twitter):  https://x.com/signup  → perfil com logo do Clima do BTC"
echo "  Instagram:    https://instagram.com → perfil business/pessoal"
echo "  Sugestão de nome: @climadobtc (ou @btc_weather_panel)"
echo "  Foto: usar o perfil-v1.png já aprovado"
echo ""
echo "PASSO 2 — Instalar o Postiz (self-hosted, grátis) no VPS:"
echo "  cd /root && git clone https://github.com/gitroomhq/postiz-app.git"
echo "  cd postiz-app && cp .env.example .env  # editar variáveis"
echo "  docker compose up -d"
echo "  Acesso: http://localhost:4200 (coloque atrás do nginx com SSL)"
echo ""
echo "PASSO 3 — Conectar as redes no Postiz:"
echo "  Settings -> Channels -> Add Channel -> escolha X e Instagram"
echo "  Autorizar via OAuth (login na própria rede)"
echo ""
echo "PASSO 4 — Gerar API key:"
echo "  Settings -> Developers -> Public API -> gerar chave"
echo "  Adicionar no .env do severino:"
echo "    POSTIZ_API_URL=https://seu-dominio-postiz.com/public/v1"
echo "    POSTIZ_API_KEY=<chave>"
echo ""
echo "PASSO 5 — Ativar automação (cron já configurado):"
echo "  O agente gera o post diário às 8:10 (junto com o card do Telegram)."
echo "  Para publicar automaticamente: node publicar_redes.js"
echo ""
echo "OBS: Até conectar as contas, o conteúdo é GERADO todos os dias em:"
echo "  /root/severino/ecosystem/data/posts_redes.json"
echo "  E você pode copiar/colar manualmente (cards prontos em card_today.png)"
echo "===================================================="
